"""CONST
Const variables for Settings.
"""

# Env (not-dotenv) vars
DOTENV_LOCATION = "DOTENV_LOCATION"

# DotEnv vars
ENDPOINT_REQUEST_TIMEOUT = "ENDPOINT_REQUEST_TIMEOUT"
API_HOST = "API_HOST"
API_PORT = "API_PORT"
API_NAME = "API_NAME"
API_DESCRIPTION = "API_DESCRIPTION"
API_VERSION = "API_VERSION"
API_LOG_LEVEL = "API_LOG_LEVEL"
HTTP_REMOTE_API = "HTTP_REMOTE_API"
WSDL_REMOTE_API = "WSDL_REMOTE_API"
HTTP_TIMEOUT = "HTTP_TIMEOUT"

# Default-fallback values
DEFAULT_API_NAME = "VigoBusAPI"
DEFAULT_API_VERSION = "0.0.1"
DEFAULT_API_HOST = "0.0.0.0"
DEFAULT_API_PORT = 5000
DEFAULT_API_LOG_LEVEL = "info"
DEFAULT_ENDPOINT_REQUEST_TIMEOUT = 30
DEFAULT_HTTP_TIMEOUT = 60
