"""CONST
Const variables for Settings.
"""

# Env (not-dotenv) vars
DOTENV_LOCATION = "DOTENV_LOCATION"

# DotEnv vars
ENDPOINT_TIMEOUT = "ENDPOINT_TIMEOUT"
API_HOST = "API_HOST"
API_PORT = "API_PORT"
API_NAME = "API_NAME"
API_DESCRIPTION = "API_DESCRIPTION"
API_VERSION = "API_VERSION"
API_LOG_LEVEL = "API_LOG_LEVEL"
HTTP_REMOTE_API = "HTTP_REMOTE_API"
WSDL_REMOTE_API = "WSDL_REMOTE_API"
HTTP_TIMEOUT = "HTTP_TIMEOUT"
WSDL_TIMEOUT = "WSDL_TIMEOUT"
HTTP_RETRIES = "HTTP_RETRIES"
STOPS_CACHE_MAXSIZE = "STOPS_CACHE_MAXSIZE"
STOPS_CACHE_TTL = "STOPS_CACHE_TTL"
BUSES_CACHE_MAXSIZE = "BUSES_CACHE_MAXSIZE"
BUSES_CACHE_TTL = "BUSES_CACHE_TTL"

# Default-fallback values
DEFAULT_API_NAME = "VigoBusAPI"
DEFAULT_API_VERSION = "0.0.1"
DEFAULT_API_HOST = "0.0.0.0"
DEFAULT_API_PORT = 5000
DEFAULT_API_LOG_LEVEL = "info"
DEFAULT_ENDPOINT_TIMEOUT = 30
DEFAULT_HTTP_TIMEOUT = 5
DEFAULT_WSDL_TIMEOUT = 10
DEFAULT_HTTP_RETRIES = 2
DEFAULT_STOPS_CACHE_MAXSIZE = 500
DEFAULT_STOPS_CACHE_TTL = 3600
DEFAULT_BUSES_CACHE_MAXSIZE = 300
DEFAULT_BUSES_CACHE_TTL = 15
