name: Test
on:
  - push

jobs:
  TestLib:
    name: Test Library @ Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install requirements
        run: python -m pip install -r vigobus/requirements.txt
      - name: Install test requirements
        run: python -m pip install -r vigobus/requirements.test.txt

      - name: Test (unit)
        working-directory: vigobus
        run: pytest -sv . -m "not real"

      - name: Test (real)
        if: ${{ matrix.python-version == '3.9' }}
        working-directory: vigobus
        run: pytest -sv . -m "real and not heavy"
